controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

token_refresh:
    path: /api/token/refresh

login_check:
    path: /api/login_check

token_invalidate:
    path: /api/token/invalidate

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

