controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_token_refresh:
    path: /api/token/refresh

api_login:
    path: /api/login_check

api_token_invalidate:
    path: /api/token/invalidate

